app = "url-shortener"
primary_region = "dfw"
kill_signal = "SIGINT"
kill_timeout = "5s"

[experimental]
  auto_rollback = true

[build]
  dockerfile = "Dockerfile"

[mounts]
  source = "url_shortener_data"
  destination = "/app/data"

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

  [[http_service.checks]]
    interval = "10s"
    timeout = "2s"
    grace_period = "5s"
    method = "GET"
    path = "/health"
    protocol = "http"

[env]
  FLASK_ENV = "production"
  PORT = "5000"
  DATABASE_URL = "sqlite:///data/urls.db"

[[vm]]
  memory = "256mb"
  cpu_kind = "shared"
  cpus = 1